# Generated by Django 3.1.4 on 2020-12-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='avaliable',
        ),
    ]
